paziresh24/patient

src/modules/profile/functions/getProfileServerSideProps.ts
src/modules/profile/functions/getProviderData.ts
src/modules/profile/functions/getUserData.ts

fix: user_id is undefined

---

src/common/components/atom/modal/modal.tsx
src/common/components/layouts/provider.tsx
src/common/hooks/useModal.ts
src/common/hooks/useSetupAppBridge.tsx
types/window.d.ts

feat: add mvp app bridge :D

---

src/modules/profile/functions/overwriteProfileData.ts

رول اوت گروه تخصصی پزشکان در پروفایل

chore: add group expertice for doctor roulout

---

src/modules/profile/events/pageView.ts
src/modules/profile/functions/overwriteProfileData.ts
src/modules/profile/views/biography/biography.tsx
src/modules/profile/views/sections.tsx
src/pages/center/[slug].tsx

حذف المنت های دستاورد ها، لینک آپارات، سوابق علمی و تایتل پروفایل

Remove doctor info element

---

src/modules/profile/functions/overwriteProfileData.ts
src/modules/profile/views/head/head.tsx
src/pages/dr/[slug].tsx

نمایش تمامی alias title برای پزشکانی که چند تخصص یکسان دارن اما alias title متفاوتی دارند

chore: fix show all alias title in doctor profile

---

README.md

Just for test

---

src/modules/booking/hooks/selectTime/useFirstFreeTime.ts
src/modules/booking/views/index.tsx
src/modules/bookingV2/views/index.tsx
src/modules/profile/views/services/bulk.tsx
src/pages/booking/[slug].tsx

افزودن قابلیت رد از مرحله انتخاب زمان در فانل بوکینگ با کوئری پارامتر -> skipTimeSelectStep

feat: skip time select booking step

---

src/modules/booking/views/factor/wrapper.tsx
src/modules/profile/views/services/onlineVisit.tsx

شفاف و قاطعانه کردن عناوین
از رزرو گفتگو به ویزیت آنلاین

feat(profile): change titles of online visit buttons in pre-invoice appointment

---

src/modules/myTurn/components/turn/footer/footer.tsx

حذف دکمه جابجایی نوبت زمانی نوبت پرداخت نشده.

feat: remove re-schedule button when the turn has not been paid

---

src/pages/index.tsx

feat: add h1 in main page

---

src/common/apis/client.ts
src/common/components/layouts/entryPoint.tsx
src/modules/login/components/mobileNumber/mobileNumber.tsx
src/modules/login/hooks/useLogin.ts
src/modules/login/store/userInfo.ts

لاگ اوت کاربر زمانی وب سرویس me خطای 401 داد

feat: me api unauthorized handle

---

src/common/components/layouts/entryPoint.tsx
src/modules/login/hooks/useLogin.ts

لاگ اوت کاربر زمانی که وب سرویس me استتوس 400 داشت.

feat: user logout when me status is 400

---

src/common/components/layouts/header/components/userProfile/userProfile.tsx

حل باگ عوض نشدن state یوزر هنگام لاگین

fix: dont change state when user login

---

src/common/components/layouts/splash.tsx
src/modules/profile/views/sections.tsx
src/modules/profile/views/services/bulk.tsx
src/modules/profile/views/services/presence.tsx
src/pages/center/[slug].tsx
src/pages/index.tsx
src/pages/s/[[...params]].tsx

امکان دریافت نوبت پزشکان دانشگاه فارس از سایت دانشگاه

can sums booking in partner site

---

src/common/apis/services/reviews/averageWaitingTime.ts
src/modules/profile/functions/getAverageWaitingTime.ts
src/modules/profile/functions/getProfileServerSideProps.ts
src/modules/profile/functions/overwriteProfileData.ts
src/modules/profile/views/services/index.tsx
src/modules/profile/views/services/onlineVisit.tsx
src/modules/profile/views/services/onlineVisitWrapper.tsx

رول اوت نمایش مدت زمان انتظار برای ویزیت آنلاین

chore: add average waiting time api for rouleout in profile

---

src/modules/profile/components/serviceCard/serviceCard.tsx
src/modules/profile/views/services/channelDetailes.tsx
src/modules/profile/views/services/index.tsx
src/modules/profile/views/services/onlineVisit.tsx
src/modules/profile/views/services/onlineVisitWrapper.tsx

افزودن تضمین بازپرداخت و مدت زمان گفتگو به کارد ویزیت انلاین

Visit online card copy

---

src/common/apis/services/profile/incrementPageView.ts
src/modules/profile/functions/getProfileServerSideProps.ts
src/modules/profile/functions/overwriteProfileData.ts
src/pages/dr/[slug].tsx

وب سرویس جدید برای پیج ویو پروفایل

feat: use increment page view new api

---

src/modules/profile/views/services/onlineVisit.tsx

اصلاح املایی و نگارشی میکروکپی های کارد دریافت ویزیت آنلاین پروفایل پزشک

fix: online visit card copywriting edits

---

src/pages/dr/[slug].tsx

فراخوانی وب سرویس پیج ویو قدیمی همراه با وب سرویس جدید پیج ویو

feat: old page view api in doctor profile call

---

src/modules/home/components/visitOnlinePromote/index.tsx
src/modules/home/components/visitOnlinePromote/visitOnlinePromote.tsx
src/modules/search/components/consultBanner/consultBanner.tsx
src/modules/search/view/recentSearch/recentSearch.tsx
src/pages/index.tsx

اضافه کردن دکمه ویزیت انلاین(پیشنهاد پزشک) به هوم پیج

feat: add visit online promote in home page

---

src/modules/dashboard/components/menuItem.tsx
src/modules/dashboard/layouts/sidebar.tsx
src/pages/api/apps.ts

پشتیبانی منو های داشبورد از تک زیر منو

feat: handle single menu dashboard

---

src/common/components/layouts/bottomNavigation/bottomNavigation.tsx

نمایش منو "مراجعین من" در global navigation برای پزشکان

feat: add doctor appoinment menu in global navigation

---

src/common/components/layouts/bottomNavigation/bottomNavigation.tsx

fix: build error for type

---

src/modules/booking/views/factor/wrapper.tsx
src/modules/dashboard/layouts/sidebar.tsx
src/modules/home/components/onlineVisitPromote/index.tsx
src/modules/home/components/onlineVisitPromote/onlineVisitPromote.tsx
src/modules/home/components/visitOnlinePromote/index.tsx
src/modules/profile/functions/overwriteProfileData.ts
src/modules/profile/views/rateReview/doctorTags.tsx
src/modules/profile/views/services/bulk.tsx
src/modules/profile/views/services/onlineVisit.tsx
src/modules/search/components/card/card.tsx
src/modules/search/components/consultBanner/consultBanner.tsx
src/pages/center/[slug].tsx
src/pages/dashboard/index.tsx
src/pages/factor/[centerId]/[bookId].tsx
src/pages/index.tsx
src/pages/receipt/[centerId]/[bookId].tsx

افزودن متن پزشک غیرفعال است به پروفایل غیرفعال
اصلاح دیزاین مودال پزشک جایگزین
پیشنهاد پزشک بصورت رندوم از 3 پزشک بالای لیست هر تخصص
اصلاح متن بالای فاکتور ویزیت  انلاین

feat: add unavailable text in doctor profile and change substitute doctor modal design

---

src/modules/dashboard/layouts/sidebar.tsx

افزدن فیچر فلگ برای منو بازارچه در داشبورد

Add feature flag for bazaar menu

---

src/common/apis/services/reviews/averageWaitingTime.ts
src/modules/profile/functions/getAverageWaitingTime.ts
src/modules/profile/functions/getProfileServerSideProps.ts

اضافه شدن بازه زمانی 30 روزه برای دریافت زمان انتظار پزشک

chore: add rage time for average waiting time api

---

src/modules/booking/views/index.tsx

حل مشکل فیلد تاریخ تولد در استعلام اطلاعات هویتی

fix: birth date input type for inquiry identity

---

src/common/services/splunk.ts
src/modules/dashboard/components/menuItem.tsx
src/modules/dashboard/layouts/sidebar.tsx
src/pages/api/apps.ts
src/pages/dashboard/apps/[...key].tsx

Add events for dashboard page

---

package-lock.json
src/modules/booking/events/selectTime.ts
src/modules/booking/views/index.tsx

اضافه شدن تفاضل بین اولین نوبت خالی در پروفایل و فلو بوکینگ در ایونت مربوط به اولین نوبت خالی

chore: add difference freeTurn profile by real in freeturn step

---

src/common/utils/isPwa.ts

رفع خطای isPwa util در سمت سرور

fix: is pwa error util in server side

---

src/modules/login/components/otpCode/otpCode.tsx
src/modules/login/views/loginForm.tsx

عوض کردن تایم ارسال کد مجدد به یک دقیقه
تماس صوتی با اولین تلاش برای ارسال مجدد کد

feat: change reset password time

---

public/.well-known/assetlinks.json

ست کردن digital asset link گوگل پلی

fix: solved problem for deep link in google paly

---

src/pages/center/[slug].tsx

افزودن فیلتر تخصص در url پروفایل مرکز درمانی

feat: add expertise url filter in center profile

---

src/pages/api/apps.ts

هندل کردن خطای وب سرویس بازارچه

fix: handle bazaar api error

---

src/common/hooks/usePwa.ts
src/pages/patient/index.tsx
src/pages/receipt/[centerId]/[bookId].tsx

اضافه شدن مدال ثبت نظر به اپلیکیشن در قبض نوبت

chore: add rate app modal in receipt

---

src/common/apis/services/auth/getUser.ts
src/common/apis/services/auth/premium/inquiryPayment.ts
src/common/apis/services/auth/premium/payment.ts
src/common/apis/services/auth/subuser/addSubuser.ts
src/common/apis/services/auth/subuser/editSubuser.ts
src/common/apis/services/auth/subuser/getSubuser.ts
src/common/apis/services/auth/subuser/removeSubuser.ts
src/common/apis/services/auth/user/updateUser.ts
src/common/apis/services/booking/book.ts
src/common/apis/services/booking/bookRequest.ts
src/common/apis/services/booking/getBookDetails.ts
src/common/apis/services/booking/getUserActiveTurnsCount.ts
src/common/apis/services/booking/moveBook.ts
src/common/apis/services/booking/removeBook.ts
src/common/apis/services/booking/termsAndConditions.ts
src/common/apis/services/bookmarks/deleteBookmark.ts
src/common/apis/services/bookmarks/getBookmarksList.ts
src/common/apis/services/factor/discountInquiry.ts
src/common/apis/services/rate/likeFeedback.ts
src/common/apis/services/rate/replyFeedback.ts
src/common/components/layouts/entryPoint.tsx
src/modules/login/hooks/useLogin.ts
src/modules/login/store/userInfo.ts
src/pages/_app.tsx

چک نکردن certificate برای بررسی لاگین بودن کاربر - ارسال نکردن certificate برای وب سرویس های clinic

feat: dont check certificate cookie

---

src/common/components/atom/badge/badge.tsx
src/common/components/atom/button/button.tsx
src/common/components/atom/timer/timer.tsx
src/pages/receipt/[centerId]/[bookId].tsx

فعال کردن پیگیری تاخیر پزشک بعد از یک ساعت از لحظه نوبت

feat: wating time follow up timer

---

src/common/apis/client.ts
src/common/components/layouts/entryPoint.tsx

ست کردن هدر Authorization برای وب سرویس کلینیک برای سایت پارتنر ها

feat: set token in clinic service header request

---

src/common/components/layouts/entryPoint.tsx
src/modules/booking/views/selectUser/selectUser.tsx
src/modules/bookingV2/views/selectUser/selectUser.tsx

حل باگ باز شدن لاگین مودال در لحظه اول باز شدن فانل بوکینگ

feat: check pending user api in select user component

---

src/pages/receipt/[centerId]/[bookId].tsx

عدم نمایش مدال ثبت ریت اپ برای دانشگاه های علوم پزشکی

fix: dont show rate app modal in receipt

---

src/common/hooks/usePwa.ts

chore: chnage store name in app

---

src/pages/factor/[centerId]/[bookId].tsx

حذف متن "* در صورتی که از زمان نوبت تا 3 ساعت بعد از آن پاسخگوی شما نبودم، نوبت شما لغو و هزینه به حساب شما باز می‌گردد." از صفحه فاکتور ویزیت آنلای

chore: remove text in online visit factor

---

src/modules/booking/views/index.tsx

تغییر ایونت Book و همچین اضافه شدن ایونت doctor profile see freeturn برای کاربرانی که از صفحه سرچ وارد فلو بوکینگ ویزیت آنلاین میشن

chore: add event for online visit book and change book event data

---

src/modules/profile/hooks/useGetFeedback.ts
src/modules/profile/views/aside.tsx
src/modules/profile/views/sections.tsx
src/modules/profile/views/seoBox/seoBox.tsx
src/modules/profile/views/services/index.tsx
src/pages/center/[slug].tsx
src/pages/dr/[slug].tsx

لینک دار کردن navigationمنوی پروفایل پزشک و مرکز

feat: add link for profile nav menu

---

src/common/services/splunk.ts
src/pages/s/[[...params]].tsx

feat: add search view event

---

src/pages/receipt/[centerId]/[bookId].tsx

حذف باکس زمان معطلی بیمار در مرکز در مدال ریت اپ

fix: remove waiting time box in rate app box

---

src/modules/profile/apis/deletedBooksRate.ts
src/modules/profile/functions/getProfileServerSideProps.ts
src/modules/profile/functions/overwriteProfileData.ts
src/modules/profile/views/activity/activity.tsx
src/modules/profile/views/activity/item.tsx
src/modules/profile/views/sections.tsx

نمایش درصد مشاوره موفق در پروفایل پزشک

feat: show deleted books rate in profile

---

src/common/components/layouts/seo.tsx
src/modules/profile/functions/getProfileServerSideProps.ts
src/modules/profile/views/head/head.tsx
src/modules/profile/views/seoBox/seoBox.tsx
src/modules/search/components/suggestion/searchBar.tsx
src/pages/_app.tsx
src/pages/_document.tsx
src/pages/center/[slug].tsx
src/pages/dr/[slug].tsx
src/styles/nprogress.css

تغییرات تکنیکالی برای سئوی صفحات
لیست تغییرات:
https://docs.google.com/document/d/19EuNAA9f45fHxm4qlXwXg6tlh_zmXGxgiHnkcb0chvk/edit

Technical seo changes

---

src/common/apis/client.ts
src/common/apis/services/reviews/averageWaitingTime.ts
src/modules/profile/functions/getAverageWaitingTime.ts
src/modules/profile/functions/getProfileServerSideProps.ts
src/modules/profile/functions/overwriteProfileData.ts

اضافه شدن لیمیت برای نمایش میانگین زمان مرکز ویزیت آنلاین در پروفایل پزشک

Average waiting time

---

src/common/services/splunk.ts
src/pages/s/[[...params]].tsx

حل باگ دوبار ارسال شدن ایونت search view

fix: search view event trigger

---

src/modules/profile/views/sections.tsx

ویرایش متن نرخ مشاوره موفق به ویزیت آنلاین موفق و ویرایش متن راهنما به این شاخص براساس تعداد ویزیت آنلاینی که پس از زمان نوبت با موفقیت انجام شده‌اند و حذف نشده‌اند محاسبه می‌شود.

fix: edit text deleted books rate in profile

---

src/modules/profile/views/listOfDoctors/listOfDoctors.tsx
src/pages/center/[slug].tsx

افزودن فانکشن debeounce به سرچ متن پروفایل مرکز

feat: add debouncing for center profile search term

---

src/common/apis/services/reviews/getReviews.ts
src/modules/profile/functions/getProfileServerSideProps.ts
src/modules/profile/functions/getReviewsData.ts
src/modules/profile/functions/overwriteProfileData.ts

دریافت نظرات پزشکان از دیسکورس و نمایش آن در پروفایل میلاد دریس

chore: get review data from ravi.paziresh24.com for one doctor

---

src/common/components/layouts/footer/data/link.ts

Helllooooo, 
I changed developer's link in the footer to prevent a 404 error.

chore: change api developers address

---

src/modules/booking/components/recommend/recommend.tsx
src/modules/profile/views/recommend/recommend.tsx

اضافه شدن لیمیت برای نمایش ریکامند کارت در پروفایل پزشکان

chore: add limit for show recommend card in profile

---

src/modules/profile/views/services/bulk.tsx

نمایش ندادن ریکامند باکس در سایت پارتنر ها

fix: dont show recommend box in bulk profile partner site

---

src/modules/profile/views/head/head.tsx

لینک به بخش نظرات با کلیک روی تعداد نظرات در سربرگ اطلاعات پزشک

fix: change review hash link in head of profile

---

src/modules/profile/functions/overwriteProfileData.ts
src/modules/profile/views/sections.tsx

تغییر متن سئو باکس انتها صفحه پروفایل پزشکان

Change seo box

---

next.config.js
src/common/apis/services/reviews/getReviews.ts
src/modules/login/components/providers/raviAuthIframe.tsx
src/modules/profile/views/rateReview/rateReview.tsx

اضافه شدن لاگین در دیسکورس برای پروفایل میلاد دریس

chore: add discourse login in profile

---

src/pages/receipt/[centerId]/[bookId].tsx

افزودن ایونت برای درخواست پشتیبانی و تاخیر پزشک در رسید نوبت

feat: add support receipt events

---

src/pages/dr/[slug].tsx

تغییر در jspn schemal پروفایل دکتر: تصحیح اسم کشور، تعیین worst rate صفر برای پروفایل پرشکان

fix: change IRN to IRR country name json schema doctor profile

---

src/modules/profile/views/sections.tsx

تغییر متن آدرس و تلفن در سئو باکس انتها صفحه پروفایل ها

chore: change center cell and address in seo box

---

src/pages/booking/[slug].tsx

با این تغییر رول اوت ایزی بوک فقط برای ویزیت انلاین اعمال میشود.

feat: use easybook just for visit online booking

---

src/modules/bookingV3/views/index.tsx

نمایش خطا دریافت اولین نوبت خالی ایزی بوک

feat: show availiability error

---

src/modules/booking/components/baseRow/baseRow.tsx
src/modules/myTurn/components/messengerButton/messengerButton.tsx
src/modules/receipt/views/bookInfo/bookInfo.tsx
src/modules/receipt/views/bookInfo/turnDetails.ts
src/pages/receipt/easybook/[bookId].tsx

تست انواع دکمه شروع گفتگو ویزیت آنلاین در صفحه قبض نوبت

Messengers button a/b test

---

src/modules/profile/functions/overwriteProfileData.ts

نمایش ندادن زمان انتظار ویزیت آنلاین در پروفایل پزشکان زمانی که دیتایی وجود نداشته باشد

chore: dont show waiting time text in profile

---

src/modules/myTurn/components/messengerButton/messengerButton.tsx
src/pages/receipt/[centerId]/[bookId].tsx

فیکس باگ نوع سوم تست دکمه شروع گفتگو قبض نوبت

fix: show color-full button

---

src/modules/booking/components/baseRow/baseRow.tsx
src/modules/receipt/views/bookInfo/turnDetails.ts

fix: show rules in receipt

---

src/modules/search/view/result/index.tsx

حذف شدن تجربه پزشک و بازدید پروفایل در سرچ کارت

chore: remove profile view and doctor experience in search card

---

src/pages/receipt/[centerId]/[bookId].tsx

نمایش  دکمه تماس با پزشک در قبض نوبت در زمانی که تماس امن برای پزشک فعال بود

feat: add secure call button in receipt page

---

src/modules/profile/functions/getProfileServerSideProps.ts
src/modules/profile/views/activity/activityWrapper.tsx
src/modules/profile/views/activity/item.tsx
src/modules/profile/views/sections.tsx

ریکوئست گرفتن تعداد نوبت های محاسبه نرخ ویزیت آنلاین را به سمت کلاینت منتقل کردم

feat: add deleted book rate in client side

---

Dockerfile
src/firebase/fcm.ts
src/modules/login/hooks/useLogin.ts
src/modules/login/store/userInfo.ts

افزودن ایونت برای تایید یا رد درخواست دسترسی به نوتیفیکشن

feat: add events for granted and denied notification

---

Dockerfile

تغییر در لایه نصب nodejs در داکرفایل

fix: change nodejs url in dockerfile

---

Dockerfile

ci: change dockerfile

---

Dockerfile
src/pages/factor/[centerId]/[bookId].tsx

حل مشکل نمایش تایم های آینده در تبدیل زمان فاکتور

fix: sameElse convert time

---

Dockerfile

حذف نسخه slim از node در داکرفایل

feat: remove slim version of node in Dockerfile

---

Dockerfile

افزودن  package-lock.json در داکرفایل

ci: add package-lock.json in dockerfile

---

Dockerfile

ci: remove libc6-compat in dockerfile

---

Dockerfile

ci: change node version to 18.17.0

---

Dockerfile

استفاده از نسخه alpine نود جی اس

feat: use node alpine version in dockerfile

---

Dockerfile
package.json

استفاده از prepare  بجای postinstall برای husky

ci: use prepare isntead of postinstall

---

.vscode/settings.json
src/modules/booking/views/factor/wrapper.tsx

برطرف شدن مشکل پرداخت برای ویزیت آنلاین در سافاری

fix: solved problem for redirect to payment in ios and app

---

src/common/components/atom/badge/badge.tsx
src/modules/profile/functions/overwriteProfileData.ts
src/modules/profile/views/rateReview/rateReview.tsx
src/modules/profile/views/sections.tsx
src/modules/rate/components/details/details.tsx
src/modules/rate/type/rate.d.ts

افوزدن متن توضیح کوتاه درباره نحوه محاسبه rate در پروفایل

feat: add hint for new rate calculations

---

src/pages/receipt/[centerId]/[bookId].tsx

افزودن ایدی پزشک و اسلاگ و سرور ایدی به ایونت تاخیر پزشک قبض نوبت

feat: add doctor_id, slug, server_id in support receipt events

---

src/modules/dashboard/layouts/sidebar.tsx
src/pages/api/apps.ts
src/pages/dashboard/apps/[...key].tsx
src/pages/dashboard/bazaar/apps.tsx
src/pages/dashboard/bazaar/services.tsx
src/pages/dashboard/index.tsx

feat: add bazaar app

---

src/modules/dashboard/layouts/sidebar.tsx
src/modules/login/store/userInfo.ts
src/pages/_app.tsx

حل مشکل set attribute گروث بوک

Growthbook  set attribute

---

src/modules/booking/components/recommend/card/card.tsx
src/modules/booking/components/recommend/recommend.tsx

اضافه شدن کارت نمایش بیشتر در انتها ریکامند کارت ها

Show more card

---

src/pages/s/[[...params]].tsx

feat: add top title in search event

---

src/modules/myTurn/components/turn/footer/footer.tsx
src/modules/myTurn/components/turn/turn.tsx
src/modules/myTurn/components/turn/turnType.ts
src/modules/profile/views/activity/activityWrapper.tsx
src/pages/patient/appointments.tsx

- قرار  دادن دکمه تماس امن در صفحه نوبت های من
- حل باگ درخواست نرخ نوبت حذف شده بدون user_center_id

My turn secure call

---

src/modules/booking/views/index.tsx
src/modules/dashboard/layouts/sidebar.tsx
src/modules/profile/store/profileData.ts
src/pages/booking/[slug].tsx

حل مشکل ریدایرکت پروفایل های منتقل شده به اسلاگ دیگه در صفحه بوکینگ

fix: booking redirection

---

src/common/components/icons/sparkle.tsx
src/modules/profile/views/rateReview/rateReview.tsx

افزودن فیچرفلک برای تگ های پزشک

feat: add gradual rollout for doctor tags feature

---

package-lock.json
package.json
public/firebase-messaging-sw.js

افزودن لاگ دریافت نوتیفیکیشن و کلیک روی نوتیفیکیشن

feat: add click and received notification log

---

src/modules/profile/functions/getProfileServerSideProps.ts
src/pages/_app.tsx

افزودن slug به اتتریبیوت های گروث بوک / فقط در سمت سرور صفحه پروفایل

feat: add slug in server profile growthbook attributes

---

src/modules/profile/views/ownPage/ownPage.tsx
src/modules/profile/views/sections.tsx

عوض کردن لینک claim و جابجایی باکس claim به بالای نظرات در پروفایل ها

feat: change claim link and postion in profile page

---

.env.development.example
src/common/apis/services/rate/getFeedbacks.ts
src/common/apis/services/rate/report.ts

Reverts paziresh24/patient#167

Revert "feat: change mizaan api base url"

---

.env.example
next.config.js
package-lock.json
package.json
plasmic-init.ts
src/modules/profile/functions/getProfileServerSideProps.ts
src/modules/profile/views/rateReview/rateReview.tsx
src/modules/profile/views/sections.tsx
src/modules/rate/type/rate.d.ts
src/modules/rate/view/rate/rate.tsx
src/pages/_app.tsx
src/pages/dr/[slug].tsx
src/styles/globals.css
tailwind.config.js

استفاده از plasmic برای کارد ریویو ها

feat: setup plasmic and add review card component

---

src/firebase/fcm.ts
src/pages/receipt/[centerId]/[bookId].tsx

دریافت دسترسی نوتیفیکشن بعد از ۸ثانیه در صفحه قبض نوبت

feat: add notification grant access in receipt

---

.eslintrc.json
next.config.js
package-lock.json
package.json

Nextjs upgrade

---

src/modules/profile/views/sections.tsx
src/modules/profile/views/waitingTimeStatistics/waitingTimeChart.tsx
src/modules/profile/views/waitingTimeStatistics/waitingTimeStatistics.tsx

Change waiting time chart font sizes

fix: waiting time statistics font sizes

---

locales/en/common.json
locales/fa/common.json
src/common/components/layouts/header/components/mobileNavbar/index.tsx
src/common/components/layouts/header/data/links.js
src/common/components/layouts/header/header.tsx

Fixes #158 
- Developers menu added to the end of menu in Desktop and Mobile.

feat: Developers menu

---

src/modules/profile/views/sections.tsx

show Cliam section when status equals to `2` every `centers`

Change claim section condition

---

src/modules/profile/views/waitingTimeStatistics/waitingTimeChart.tsx

Fix waiting time statistics pie chart label position

Fix waiting time statistics pie chart label position

---

.vscode/settings.json
src/modules/search/components/suggestion/suggestionAtoms/citySelect/citySelect.tsx

only incorrect "جستجوی" word corrected in the City Search Box Placeholder Text.

feat: Enhance City Search Box Placeholder Text

---

src/common/apis/services/booking/establishingSecureCall.ts
src/pages/receipt/[centerId]/[bookId].tsx

Change secure call and doctor delay follow up workflow api to api gateway

fix: change secure call and doctor delay follow up workflow api to api gateway

---

src/modules/search/components/filters/mobileToolbar/index.tsx
src/modules/search/view/suggestion/suggestion.tsx

Related issue: https://github.com/paziresh24/patient/issues/162
- Landing navItems style
- feat: Filters sortBy active

Enhance user accessibility to filters

---

src/firebase/fcm.ts
src/pages/receipt/[centerId]/[bookId].tsx

Check browser notification support, crashed page because browser not supported.

Cehck browser notification support

---

locales/fa/search.json

changed placeholder text from مرکز درمانی to بیمارستان

Fix: Update Search Box Placeholder Text for Improved User Comprehension

---

src/modules/search/view/recentSearch/recentSearch.tsx
src/pages/apphome.tsx
src/pages/index.tsx

Add grid and suggestion type to app home.

feat: add app home ui types

---

src/modules/booking/components/userCard/userCard.tsx
src/modules/booking/views/selectUser/selectUser.tsx
src/modules/booking/views/selectUser/wrapper.tsx

Clarifying loading indicator

---

src/pages/login/index.tsx

check redirect_url login page white list

feat: check redirect_url login page white list

---

src/pages/apphome.tsx

Add general practitioner online visit promote in app home

chore: add online visit promote in app home

---

src/common/fragment/components.tsx
src/common/fragment/fragment.tsx
src/modules/profile/views/sections.tsx
src/pages/login/index.tsx

use About fragment in doctor profile

feat: use About fragment in doctor profile

---

src/common/fragment/components.tsx
src/common/fragment/fragment.tsx
src/modules/profile/views/sections.tsx
src/pages/login/index.tsx

Reverts paziresh24/patient#225

Revert "feat: use About fragment in doctor profile"

---

src/common/fragment/components.tsx
src/common/fragment/fragment.tsx
src/modules/profile/views/sections.tsx
src/pages/login/index.tsx

Reverts paziresh24/patient#226

Revert "Revert "feat: use About fragment in doctor profile""

---

src/modules/search/components/suggestion/suggestionSection/slider.tsx
src/pages/receipt/[centerId]/[bookId].tsx

Add average rate to top doctors

---

src/modules/search/view/result/index.tsx
src/pages/receipt/[centerId]/[bookId].tsx

Direct splunk request for Search Click Position

---

.env.example
next.config.js
src/modules/patient/views/bookmarksList.tsx
src/modules/profile/views/sections.tsx
src/modules/search/components/card/card.tsx
src/modules/search/components/categoryCard/categoryCard.tsx
src/modules/search/components/suggestion/suggestionSection/card.tsx
src/modules/search/components/suggestion/suggestionSection/slider.tsx
src/pages/booking/[slug].tsx
src/pages/booking/easybook/[slug].tsx
src/pages/center/[slug].tsx
src/pages/dr/[slug].tsx
src/pages/factor/[centerId]/[bookId].tsx
src/pages/receipt/[centerId]/[bookId].tsx
src/pages/receipt/easybook/[bookId].tsx

Change cdn base url for images

---

src/pages/apphome.tsx

remove app home design feature flagging

chore: remove app home design feature flagging

---

src/modules/search/components/suggestion/searchBar.tsx
src/modules/search/components/suggestion/suggestionAtoms/citySelect/citySelect.tsx
src/modules/search/view/suggestion/suggestion.tsx
src/pages/receipt/[centerId]/[bookId].tsx

Loading during gps retrieval

---

src/modules/search/view/result/index.tsx

fix: change condition for search result render

fix: change condition for search result render

---

src/pages/_app.tsx

add skip flags cache for growthbook

feat: add skip flags cache

---

src/firebase/fcm.ts

fix firebase sw error
DOMException: Failed to execute 'subscribe' on 'PushManager': Subscription failed - no active Service Worker

fix: get or register firebase service worker

---

src/modules/myTurn/components/turn/footer/footer.tsx

Due to the fact that the deposit amount must be included for the doctor, appointments within the unauthorized period should not be canceled

appointments within the unauthorized period should not be canceled

---

src/modules/myTurn/components/turn/footer/footer.tsx

change title of unrefundable book alert

change title of unrefundable book alert

---

src/common/hooks/useCustomize.ts
src/modules/booking/views/selectUser/selectUser.tsx
src/modules/login/components/mobileNumber/mobileNumber.tsx
src/modules/login/context/loginModal.tsx
src/modules/login/views/loginModal.tsx

Add oauth button in login modal

feat: add oauth button in login modal

---

src/modules/login/components/mobileNumber/mobileNumber.tsx

feat: add loading for oauth button

---

src/modules/booking/views/factor/wrapper.tsx
src/modules/profile/views/rateReview/rateReview.tsx

feat: add FinancialTransactions and RateAndReview filter selected splunk event

Add FinancialTransactions payment button clicked and RateAndReview filter selected splunk event

---

src/common/components/layouts/entryPoint.tsx
src/modules/search/view/result/index.tsx
src/pages/center/[slug].tsx
src/pages/s/[[...params]].tsx

remove search code component and search result feature flag

feat: remove search code component and search result feature flag

---

src/modules/login/components/mobileNumber/mobileNumber.tsx
src/pages/login/index.tsx

feat: add token params in login page

Add token params in login page

---

src/modules/bookingV2/views/index.tsx
src/modules/profile/views/services/bulk.tsx

show services error in booking

feat: show services error in booking

---

src/common/apis/services/booking/book.ts
src/common/apis/services/booking/bookRequest.ts
src/common/apis/services/booking/getFreeDays.ts
src/common/apis/services/booking/getFreeTurn.ts
src/common/apis/services/booking/getFreeTurns.ts
src/common/apis/services/booking/suspend.ts
src/common/apis/services/booking/unsuspend.ts
src/modules/booking/hooks/booking.ts
src/modules/booking/views/index.tsx
src/pages/api/apps.ts

Add configurable booking api endpoints

feat: add configurable booking api endpoints

---

src/common/hoc/withServerUtils.ts
src/modules/profile/views/services/onlineVisitWrapper.tsx

fix: send user_center_id for book api

---

src/common/apis/services/profile/internalLinks.ts

Add timeout for internal link api

chore: add timeout for internal link api

---

src/common/components/layouts/header/data/links.js

change to https://www.paziresh24.com/home/intermediate-registration-form/?header

change doctor register link in header

---

src/common/components/layouts/footer/footer.tsx

change to https://www.paziresh24.com/home/intermediate-registration-form/?footer

change doctor register link in footer

---

src/common/fragment/growthbookGlobalContext.tsx
src/common/hooks/useCustomize.ts
src/modules/profile/views/listOfDoctors/listOfDoctors.tsx
src/pages/_app.tsx
src/pages/fragment/index.tsx

Add Growthbook action to fragment(plasmic studio)

feat: add growthbook to fragment

---

src/common/apis/services/reviews/getReviews.ts
src/modules/profile/functions/getProfileServerSideProps.ts
src/modules/profile/views/rateReview/fragmentRateReview.tsx

feat: change review order to default_order

---

.plasmic/plasmic/ravi_r_r/PlasmicReviewList.tsx
plasmic.lock
src/common/apis/services/reviews/getReviews.ts

Reverts paziresh24/patient#337

Revert "[plasmic] Sync project ravi (r&r)"

---

src/modules/myTurn/components/turn/body/body.tsx

feat: dont show feedback link in patient appointments list

---

src/pages/dashboard/apps/[...key].tsx

add session-duration and active-users log per app

feat: add hamdast app user engagement log

---

src/modules/profile/views/sections.tsx
src/pages/dr/[slug].tsx

feat: change rating value in profile seo box

---

src/modules/search/hooks/useSuggestionItemClick.ts

fix: open scroll when click suggestion item

---

src/modules/dashboard/apis/apps.ts
src/modules/dashboard/layouts/sidebar.tsx
src/pages/api/apps.ts
src/pages/dashboard/apps/[...key].tsx
src/pages/dashboard/index.tsx

feat: change hamdast api for installations apps

---

src/modules/search/components/suggestion/suggestionSection/slider.tsx
src/modules/search/constants/suggestion/categoryIcons/icons/star.tsx

feat: change suggestion rate api

---

src/common/apis/serverStateKeysEnum.ts
src/common/apis/services/booking/availabilityStatus.ts
src/modules/profile/views/aside.tsx
src/modules/profile/views/services/index.tsx
src/modules/search/constants/suggestion/categoryIcons/index.ts

feat: use availability-status core booking api

---

.plasmic/plasmic/paziresh_24_search/PlasmicProductCard.tsx
.plasmic/plasmic/paziresh_24_search/PlasmicSearchResults.module.css
.plasmic/plasmic/paziresh_24_search/PlasmicSearchResults.tsx
.plasmic/plasmic/paziresh_24_search/icons/PlasmicIcon__Icon7.tsx
plasmic.json
plasmic.lock

ارسال لاگ مشاهده کارد پیشنهاد ویزیت آنلاین

---

locales/en/common.json
locales/fa/common.json
src/common/components/layouts/header/components/mobileNavbar/index.tsx
src/common/components/layouts/header/data/links.js
src/common/components/layouts/header/header.tsx

feat: add pricing medical center menu header

---

src/common/apis/services/reviews/averageWaitingTime.ts

chore: add timeout for average time api

---

src/common/apis/services/reviews/averageWaitingTime.ts
src/common/components/layouts/header/data/links.js
src/modules/profile/functions/getAverageWaitingTime.ts
src/modules/profile/functions/getProfileServerSideProps.ts
src/modules/profile/functions/overwriteProfileData.ts

Reverts paziresh24/patient#430

Revert "feat: use center avg time api and change medical center register link"

---

src/common/services/plasmicSplunkEvent.ts
src/pages/fragment/index.tsx

feat: add api_host field for splunk service

---

src/modules/profile/functions/getProfileServerSideProps.ts

chore: use online visit book count from fulle profile

---

src/common/components/layouts/bottomNavigation/bottomNavigation.tsx
src/common/components/layouts/header/header.tsx
src/common/components/layouts/layoutWithHeaderAndFooter.tsx
src/pages/dashboard/apps/[...key].tsx
src/pages/dr/[slug].tsx

fix: app layout size

---

src/modules/login/store/userInfo.ts

fix: remove withCredentials flag for logout api in univerisy

---

src/common/services/splunk.ts
src/modules/booking/views/index.tsx

feat: add choose subuser event load page

---

src/modules/dashboard/components/menuItem.tsx
src/modules/dashboard/layouts/sidebar.tsx

feat: add unread for menu

---

package-lock.json
package.json
src/common/fragment/components/api-request.tsx
src/common/fragment/designSystemGlobalContext.tsx
src/modules/profile/views/head/head.tsx
src/modules/profile/views/rateReview/fragmentRateReview.tsx
src/modules/search/view/result/index.tsx
src/pages/_app.tsx
src/pages/fragment/index.tsx

refactor: add swr and plasmic global contexts providers

---

src/common/components/layouts/layoutWithHeaderAndFooter.tsx
src/pages/fragment/index.tsx

feat: add paziresh24 layout with header and footer component to plasmic

---

src/common/components/atom/switch/switch.tsx
src/common/fragment/components/switch.tsx
src/common/fragment/splunk.tsx
src/pages/fragment/index.tsx

refactor: update switch component and add Splunk global context

---

.plasmic/plasmic/paziresh_24_search/PlasmicProductCard.module.css
.plasmic/plasmic/paziresh_24_search/PlasmicProductCard.tsx
.plasmic/plasmic/paziresh_24_search/PlasmicSearchResults.tsx
plasmic.lock

add first_free_time_data_src_from_availability-status_api 

---

src/modules/profile/views/listOfDoctors/listOfDoctors.tsx
src/pages/center/[slug].tsx

fix: feature flag for center profile search result

---

src/pages/fragment/index.tsx

fix: fragment/pwa export name

---

src/modules/login/components/otpCode/otpCode.tsx
src/modules/login/components/password/password.tsx

feat: send event after succsess login api

---

src/modules/profile/views/sections.tsx

fix doctor biography

---

.plasmic/plasmic/paziresh_24_search/PlasmicGlobalContextsProvider.tsx
.plasmic/plasmic/paziresh_24_search/plasmic.module.css
.plasmic/plasmic/plasmic__default_style.module.css
plasmic.json
plasmic.lock

Reverts paziresh24/patient#727

Revert "[plasmic] Sync project Paziresh24/Search"

---

.plasmic/plasmic/paziresh_24_profile/PlasmicGlobalContextsProvider.tsx
.plasmic/plasmic/paziresh_24_search/PlasmicSearchResults.module.css
.plasmic/plasmic/paziresh_24_search/PlasmicSearchResults.tsx
plasmic.json
plasmic.lock

This is an automated commit generated by Ebrahim Ghane using Plasmic (https://plasmic.app/).
Project name: Paziresh24/Search
Project URL: https://studio.plasmic.app/projects/sMdpLWyxbzDCruwMRffW2m
- What are the minimal test data …

[plasmic] Sync project Paziresh24/Search

---

src/modules/search/view/result/index.tsx

add all city object to search result component

---

src/common/hooks/useModal.ts
src/modules/hamdast/components/auth.tsx
src/modules/hamdast/components/payment.tsx
src/modules/profile/views/aside.tsx
src/modules/profile/views/services/index.tsx
src/pages/_/[app_key]/[...params].tsx
src/pages/dr/[slug].tsx

Hamdast login pyament modal

---

src/pages/booking/[slug].tsx

remove use of users in booking page.

refactor: remove use of useProfile in booking page

---

src/common/components/layouts/header/components/userProfile/userProfile.tsx
src/modules/dashboard/layouts/sidebar.tsx
src/pages/dashboard/profile.tsx

feat: add support menu button to user profile and sidebar

---

.plasmic/plasmic/paziresh_24/PlasmicServices.module.css
.plasmic/plasmic/paziresh_24/PlasmicServices.tsx
plasmic.json
plasmic.lock

Reverts paziresh24/patient#798

Revert "[plasmic] Sync project Paziresh24"

---

src/pages/receipt/[centerId]/[bookId].tsx

remove use of provider name in receipt

fix: remove use of profile name from receipt component

---

src/modules/myTurn/components/turn/footer/footer.tsx
src/pages/_app.tsx
src/pages/receipt/[centerId]/[bookId].tsx

chore: use growthbook background sysnc option

---

src/common/components/layouts/bottomNavigation/bottomNavigation.tsx
src/pages/patient/index.tsx

- Add handling for unauthenticated users in bottom navigation
- Implement launcher flag check in patient profile routing
- Correct dashboard menu item spelling
- Enhance routing conditions based on feature flags

fix: Update bottom navigation and patient profile routing logic

---

src/common/components/layouts/footer/data/link.ts
src/common/components/layouts/header/data/links.js

- Changed job opportunities link in footer to point to the correct URL
- Updated API documentation link in header to the new endpoint

fix: Update footer and header links for job opportunities and API documentation

---

src/modules/profile/components/head/toolBar.tsx
src/modules/profile/hooks/useToolBarController.ts
src/modules/profile/views/aside.tsx
src/modules/profile/views/centersInfo/actionButton.tsx

- Added InfoIcon to the toolbar for reporting
- Updated routing logic in the toolbar to include user cell information
- Introduced ActionButton component for reporting errors in center information
- Refactored aside component to utilize the new ActionButton

feat: Enhance toolbar and aside components with new action button

---

src/pages/receipt/[centerId]/[bookId].tsx

- Introduced logic to fetch holidays from an external API based on the appointment date range
- Implemented checks to determine if the appointment falls between holidays
- Displayed an alert message to inform users if their appointment is scheduled during a holiday period

feat: Add holiday detection for appointment dates in receipt page

---

src/common/apis/serverStateKeysEnum.ts
src/common/apis/services/wallet/getBalance.ts
src/modules/booking/components/factor/invoice/invoice.tsx
src/modules/booking/views/factor/factor.tsx
src/modules/booking/views/factor/wrapper.tsx
src/pages/factor/[centerId]/[bookId].tsx

- Introduced a new API service to fetch wallet balance.
- Updated ServerStateKeysEnum to include WalletBalance.
- Enhanced Invoice component to display wallet balance and service fee details.
- Integrated wallet balance fetching into the Factor view based on feature flag.

feat: Add wallet balance functionality and enhance invoice component

---

Dockerfile
curl_logger.sh
entrypoint.sh

add curl metrics logger to splunk

add curl logger script

---

.github/workflows/gitlab-sync.yml

add github action file to force immediate sync to gitlab.

add github action to force immediate sync to gitlab

---

.github/workflows/gitlab-sync.yml

add read permission to action

---

src/modules/search/view/suggestion/suggestion.tsx

fix: close modal with back button

---

src/common/apis/services/doctor/getDoctorFullName.ts
src/modules/profile/functions/getAggregatedProfileData.ts

- Cleaned up code formatting and removed unnecessary whitespace.
- Updated API endpoint in getAggregatedProfileData to fetch doctor information from the correct URL.
- Renamed variables for clarity and consistency in handling doctor data.
- Enhanced error handling and logging for better debugging.

Refactor getDoctorFullName and getAggregatedProfileData functions

---

src/common/apis/services/doctor/getDoctorImage.ts
src/modules/profile/functions/getAggregatedProfileData.ts
src/modules/profile/functions/getProfileServerSideProps.ts
src/modules/profile/functions/overwriteProfileData.ts
src/modules/profile/hooks/useProfileClientFetch.ts

New profile pic for doc

---

src/common/apis/services/doctor/getDoctorBiography.ts
src/modules/profile/functions/getAggregatedProfileData.ts
src/modules/profile/functions/getProfileServerSideProps.ts
src/modules/profile/functions/overwriteProfileData.ts
src/modules/profile/hooks/useProfileClientFetch.ts

feat: integrate doctor biography API and update profile data handling

---

src/common/hooks/usePwa.ts

Update usePwa.ts for market to google play link

---

src/common/hooks/usePwa.ts

Update usePwa.ts to navigate user direct to rate intent of bazaar store
